export const WEEKLY_TEST_QUESTIONS = [
  "I felt motivated throughout the week.",
  "I was able to focus on my daily tasks.",
  "I managed my stress effectively.",
  "I experienced a stable mood most days.",
  "I maintained a consistent sleep schedule.",
  "I felt physically energetic this week.",
  "I engaged in social interaction comfortably.",
  "I felt optimistic about my personal goals.",
  "I managed my time well this week.",
  "I avoided overthinking minor issues.",
  "I practiced mindfulness or relaxation.",
  "I maintained a healthy diet.",
  "I felt in control of my emotions.",
  "I avoided procrastination.",
  "I was kind to myself when I made mistakes.",
  "I reached out for help when needed.",
  "I handled unexpected challenges calmly.",
  "I stayed away from negative influences.",
  "I took small steps toward self-improvement.",
  "I felt connected with my purpose.",
  "I didn’t feel overwhelmed by responsibilities.",
  "I balanced work and rest effectively.",
  "I limited screen time and distractions.",
  "I reflected on my progress this week.",
  "I felt satisfied with my personal relationships.",
  "I took time to enjoy hobbies or interests.",
  "I experienced gratitude regularly.",
  "I maintained confidence in decision-making.",
  "I expressed emotions in a healthy way.",
  "I had a generally positive week.",
  "I avoided negative self-talk.",
  "I learned something new about myself.",
  "I managed anxiety when it appeared.",
  "I accepted things beyond my control.",
  "I felt hopeful about the future.",
  "I had a sense of accomplishment.",
  "I communicated effectively with others.",
  "I practiced good posture and breathing.",
  "I felt emotionally supported.",
  "I took time to rest when needed.",
  "I avoided comparing myself to others.",
  "I felt grateful for small things.",
  "I believed in my ability to improve.",
  "I had meaningful moments this week.",
  "I practiced patience in stressful situations.",
  "I showed empathy toward others.",
  "I took responsibility for my actions.",
  "I felt proud of my progress.",
  "I am ending this week with a peaceful mind.",
];

export const WEEKLY_TEST_OPTIONS = [1, 2, 3, 4, 5];
